language: cpp
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt594-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt59-meta-minimal
  - sudo apt-get -y install qt59creator

services:
  - postgresql

env:
  - TEST=t1
  - TEST=t2

script:
  - source /opt/qt59/bin/qt59-env.sh
  - mkdir build && cd build
  - /opt/qt59/bin/qmake ../TravisTest.pro
  - make
    #  - g++ test.cpp
