language: cpp
sudo: required
dist: trusty

before_install:
  - sudo add-apt-repository --yes ppa:beineri/opt-qt58-trusty
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt58 qt58serialbus 

script:
  - source /opt/qt58/bin/qt58-env.sh
  - /opt/qt58/bin/qmake
  - make
