configuration:
  - Debug
  - Release
environment:
  matrix:
    - TEST_ENV: "val1"
    - TEST_ENV: "val2"
image:
- Visual Studio 2017
install:
- set QTDIR=C:\Qt\5.11.2\msvc2017_64
- set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\Tools\QtCreator\bin\
for:
-
  matrix:
    only:
      - configuration: Debug
  environment:
    QBS_ENV: "debug"
-
  matrix:
    only:
      - configuration: Release
  environment:
    QBS_ENV: "release"
  build_script:
    - cmd: echo release build
      
build_script:
- cmd: ECHO %QBS_ENV%
- cmd: qmake --version
- cmd: qbs --version
- cmd: qbs --version
