configuration:
  - mingw53_32
  - msvc2017_64

environment:
  matrix:
    - PROJECT_BUILD_MODE: debug
    - PROJECT_BUILD_MODE: release

image:
- Visual Studio 2017

install:
# - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\Tools\QtCreator\bin\

for:
-
  matrix:
    only:
      - configuration: mingw53_32
  environment:
    QT_PATH: C:\Qt\5.11.2\mingw53_32
  before_build:
    - set PATH=%QT_PATH%\bin;C:\Qt\Tools\QtCreator\bin\;%PATH%
    - qtenv2.bat
    - qbs setup-toolchains --detect
    - qbs setup-qt --detect
    - cd C:\projects\travistest
-
  matrix:
    only:
      - configuration: msvc2017_64
  environment:
    QT_PATH: C:\Qt\5.11.2\msvc2017_64
  before_build:
    - set PATH=%QT_PATH%\bin;C:\Qt\Tools\QtCreator\bin\;%PATH%
    - qtenv2.bat
    - qbs setup-toolchains --detect
    - qbs setup-qt --detect
    - cd C:\projects\travistest
      
build_script:
- cmd: qbs build profile:qt-5-11-2 config:$(PROJECT_BUILD_MODE)
