environment:
- QBS_ENV: debug
- QBS_ENV: release
image:
- Visual Studio 2017
install:
- set QTDIR=C:\Qt\5.11.2\msvc2017_64
- set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\Tools\QtCreator\bin\
build_script:
- cmd: ECHO build script
- cmd: qmake --version
- cmd: qbs --version
- cmd: qbs --version
