configuration:
  - Debug
  - Release

environment:
  matrix:
    - QT_PATH: C:\Qt\5.11.2\mingw53_32
    - QT_PATH: C:\Qt\5.11.2\msvc2017_64

image:
- Visual Studio 2017

init:
- set PATH=%QT_PATH%\bin
- qtenv2.bat

install:
# - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin;C:\Qt\Tools\QtCreator\bin\

for:
-
  matrix:
    only:
      - configuration: Debug
  environment:
    QBS_ENV: "debug"
-
  matrix:
    only:
      - configuration: Release
  environment:
    QBS_ENV: "release"
  build_script:
    - cmd: echo release build
    - cmd: qbs setup-toolchains --detect
    - cmd: qbs config --list profiles
      
build_script:
- cmd: ECHO %QBS_ENV%
- cmd: qmake --version
- cmd: qbs --version
- cmd: qbs --version
- cmd: qbs setup-toolchains --detect
- cmd: qbs config --list profiles
